# Generated by Django 6.0.5 on 2026-05-27 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iep_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('lessonID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('lessonContent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('iep_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='iep_management.iepgoal')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingStrategy',
            fields=[
                ('strategyID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('strategyContent', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('iep_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_strategies', to='iep_management.iepgoal')),
            ],
        ),
        migrations.CreateModel(
            name='VisualAid',
            fields=[
                ('visualAidID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('imageUrl', models.URLField(max_length=500)),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('iep_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_aids', to='iep_management.iepgoal')),
            ],
        ),
    ]
