# Generated by Django 6.0.5 on 2026-05-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iep_management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('lessonID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('iep', models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iep')),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingStrategy',
            fields=[
                ('strategyID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('strategyContent', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('iep', models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iep')),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VisualAid',
            fields=[
                ('visualAidID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('imageUrl', models.URLField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('iep', models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iep')),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
    ]
