# Generated by Django 6.0.5 on 2026-05-27 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0006_remove_iep_student'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='iep',
            field=models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iepmodel'),
        ),
        migrations.AlterField(
            model_name='teachingstrategy',
            name='iep',
            field=models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iepmodel'),
        ),
        migrations.AlterField(
            model_name='visualaid',
            name='iep',
            field=models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iepmodel'),
        ),
    ]
