# Generated by Django 6.0.5 on 2026-05-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0007_delete_iep'),
        ('resources', '0002_alter_lessonplan_iep_alter_teachingstrategy_iep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='iep',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachingstrategy',
            name='iep',
        ),
        migrations.RemoveField(
            model_name='teachingstrategy',
            name='student',
        ),
        migrations.RemoveField(
            model_name='visualaid',
            name='iep',
        ),
        migrations.RemoveField(
            model_name='visualaid',
            name='student',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='iep_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='iep_management.iepgoal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lessonContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingstrategy',
            name='iep_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_strategies', to='iep_management.iepgoal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaid',
            name='iep_goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visual_aids', to='iep_management.iepgoal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visualaid',
            name='prompt_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(default='Draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='visualaid',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
