# Generated by Django 6.0.5 on 2026-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_visualaid_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualaid',
            name='steps_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
