# Generated by Django 6.0.5 on 2026-05-27 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_relax_student_profile_and_profiledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('assessmentType', models.CharField(max_length=255)),
                ('result', models.TextField(blank=True, default='')),
                ('dateTaken', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IEPModel',
            fields=[
                ('iepID', models.AutoField(primary_key=True, serialize=False)),
                ('baselineData', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='')),
                ('accommodations', models.TextField(blank=True, default='')),
                ('generatedDetails', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('program_type', models.CharField(choices=[('Graded', 'Graded (K-12)'), ('Non-Graded', 'Non-Graded (Functional)')], default='Graded', max_length=50)),
                ('difficulties', models.TextField(blank=True, help_text='Enter ALL areas of difficulty', null=True)),
                ('learning_barriers', models.TextField(blank=True, help_text='Factors restricting participation', null=True)),
                ('barrier_qualifiers', models.CharField(blank=True, max_length=255, null=True)),
                ('learning_facilitators', models.TextField(blank=True, help_text='Factors enabling participation', null=True)),
                ('facilitator_qualifiers', models.CharField(blank=True, max_length=255, null=True)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ieps', to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IEPGoal',
            fields=[
                ('goalID', models.AutoField(primary_key=True, serialize=False)),
                ('goalName', models.CharField(max_length=255)),
                ('target_metric', models.CharField(max_length=255)),
                ('subject_category', models.CharField(blank=True, help_text='e.g., CARE SKILLS, Mathematics', max_length=255, null=True)),
                ('annual_goal', models.TextField(blank=True, help_text='Annual Goal/Long Term', null=True)),
                ('iep', models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, related_name='individual_goals', to='iep_management.iepmodel')),
            ],
        ),
        migrations.CreateModel(
            name='IEPObjectiveRow',
            fields=[
                ('rowID', models.AutoField(primary_key=True, serialize=False)),
                ('enroute_objectives', models.TextField(blank=True, help_text='Harvest from K-12 Curriculum', null=True)),
                ('interventions_procedures', models.TextField(blank=True, help_text='Interventions/Activities/Procedure', null=True)),
                ('timeline_mins_session', models.CharField(blank=True, help_text='e.g., 15 to 20 minutes every day', max_length=255, null=True)),
                ('individuals_responsible', models.CharField(blank=True, help_text='e.g., SNED Teacher, Parents', max_length=255, null=True)),
                ('progress_instructional', models.TextField(blank=True, help_text='Progress/Instructional Evaluation', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Handwritten based on actual learning', null=True)),
                ('parent_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_rows', to='iep_management.iepgoal')),
            ],
        ),
    ]
