# Generated by Django 6.0.5 on 2026-05-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('assessmentType', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('dateTaken', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IEP',
            fields=[
                ('iepID', models.AutoField(primary_key=True, serialize=False)),
                ('baselineData', models.TextField()),
                ('goals', models.TextField()),
                ('accomodations', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IEPGoal',
            fields=[
                ('goalID', models.AutoField(primary_key=True, serialize=False)),
                ('goalName', models.CharField(max_length=255)),
                ('target_metric', models.CharField(max_length=255)),
                ('iep', models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iep')),
            ],
        ),
    ]
