# Generated by Django 6.0.5 on 2026-05-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IEPModel',
            fields=[
                ('iepID', models.AutoField(primary_key=True, serialize=False)),
                ('baselineData', models.TextField()),
                ('goals', models.TextField()),
                ('accommodations', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ieps', to='users.studentprofile')),
            ],
        ),
    ]
