# Generated by Django 5.0.10 on 2026-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0002_generatedaiinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedaiinsight',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iepmodel',
            name='baselineData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iepmodel',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
