# Generated by Django 6.0.5 on 2026-05-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0002_iepmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iepgoal',
            name='iep',
            field=models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, related_name='individual_goals', to='iep_management.iepmodel'),
        ),
    ]
