# Generated by Django 6.0.5 on 2026-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0002_generatedaiinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iepmodel',
            name='baselineData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iepmodel',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
