# Generated by Django 6.0.5 on 2026-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0005_alter_assessment_result_alter_iep_accomodations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iep',
            name='student',
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='annual_goal',
            field=models.TextField(blank=True, help_text='Annual Goal/Long Term', null=True),
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='enroute_objectives',
            field=models.TextField(blank=True, help_text='Harvest from K-12 Curriculum', null=True),
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='individuals_responsible',
            field=models.CharField(blank=True, help_text='e.g., SNED Teacher, Parents', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='interventions_procedures',
            field=models.TextField(blank=True, help_text='Interventions/Activities/Procedure', null=True),
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='progress_instructional',
            field=models.TextField(blank=True, help_text='Progress/Instructional Evaluation', null=True),
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='remarks',
            field=models.TextField(blank=True, help_text='Handwritten based on actual learning', null=True),
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='subject_category',
            field=models.CharField(blank=True, help_text='e.g., CARE SKILLS, Mathematics', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iepgoal',
            name='timeline_mins_session',
            field=models.CharField(blank=True, help_text='e.g., 15 to 20 minutes every day', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iepmodel',
            name='barrier_qualifiers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iepmodel',
            name='difficulties',
            field=models.TextField(blank=True, help_text='Enter ALL areas of difficulty', null=True),
        ),
        migrations.AddField(
            model_name='iepmodel',
            name='facilitator_qualifiers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iepmodel',
            name='learning_barriers',
            field=models.TextField(blank=True, help_text='Factors restricting participation', null=True),
        ),
        migrations.AddField(
            model_name='iepmodel',
            name='learning_facilitators',
            field=models.TextField(blank=True, help_text='Factors enabling participation', null=True),
        ),
        migrations.AddField(
            model_name='iepmodel',
            name='program_type',
            field=models.CharField(choices=[('Graded', 'Graded (K-12)'), ('Non-Graded', 'Non-Graded (Functional)')], default='Graded', max_length=50),
        ),
    ]
