# Generated by Django 6.0.5 on 2026-05-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0005_alter_assessment_result_alter_iep_accomodations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iep',
            name='student',
        ),
    ]
