# Generated by Django 6.0.5 on 2026-09-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0005_iepmodel_unique_student_iep_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='iepmodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
