# Generated by Django 6.0.5 on 2026-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0006_iepmodel_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='iepobjectiverow',
            name='month_1_target',
            field=models.TextField(blank=True, help_text='Month 1 Milestone (1st Month)', null=True),
        ),
        migrations.AddField(
            model_name='iepobjectiverow',
            name='month_2_target',
            field=models.TextField(blank=True, help_text='Month 2 Milestone (2nd Month)', null=True),
        ),
        migrations.AddField(
            model_name='iepobjectiverow',
            name='month_3_target',
            field=models.TextField(blank=True, help_text='Month 3 Milestone (3rd Month)', null=True),
        ),
    ]
