# Generated by Django 6.0.5 on 2026-05-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iep_management', '0006_remove_iep_student_iepgoal_annual_goal_and_more'),
        ('resources', '0002_alter_lessonplan_iep_alter_teachingstrategy_iep_and_more'),
        ('tracking', '0003_alter_progressreport_iep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IEP',
        ),
    ]
