# Generated by Django 6.0.5 on 2026-05-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iep_management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(db_column='teacherID', on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('overallStatus', models.CharField(max_length=255)),
                ('iep', models.ForeignKey(db_column='iepID', on_delete=django.db.models.deletion.CASCADE, to='iep_management.iep')),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('actionTaken', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(db_column='teacherID', on_delete=django.db.models.deletion.RESTRICT, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProcessingLog',
            fields=[
                ('progressID', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
                ('performanceScore', models.CharField(max_length=100)),
                ('dateRecorded', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
                ('teacher', models.ForeignKey(db_column='teacherID', on_delete=django.db.models.deletion.RESTRICT, to='users.teacher')),
            ],
        ),
    ]
