# Generated by Django 6.0.5 on 2026-05-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('progressID', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
                ('performanceScore', models.IntegerField()),
                ('dateLogged', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
    ]
