# Generated by Django 6.0.5 on 2026-05-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwordHash', models.CharField(max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('studentID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('asdBackground', models.TextField()),
                ('preferences', models.TextField()),
                ('assessmentResult', models.TextField()),
                ('profileStatus', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(db_column='teacherID', on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
