# Generated by Django on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_relax_student_profile_and_profiledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='has_completed_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
