# Generated by Django 6.0.5 on 2026-09-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacher_has_completed_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='consent_date',
            field=models.DateField(blank=True, help_text='Date when parental/guardian consent was verified', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, default='', help_text='Full legal name of consenting parent or legal guardian', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='Parent', help_text='Relationship of consenting guardian to minor (e.g. Mother, Father, Legal Guardian)', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parental_consent_obtained',
            field=models.BooleanField(default=False, help_text='Explicit parental or legal guardian consent obtained under RA 10173'),
        ),
    ]
