# Generated by Django 6.0.5 on 2026-10-04 21:02

import users.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_created_at_studentprofile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='asdBackground',
            field=users.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assessmentResult',
            field=users.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='diagnosis',
            field=users.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=users.fields.EncryptedCharField(blank=True, default='', help_text='Full legal name of consenting parent or legal guardian', max_length=512),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=users.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
    ]
